---
# Playbook to deploy Ansible Tower

- name: Install Tower to VM
  hosts: tower
  vars:
    tower_manage_base_packages:
      - ansible-tower-cli
      - gcc
      - rsync
      - python-devel
      - krb5-devel
      - krb5-libs
      - krb5-workstation
    tower_manage_aws_rhui_repos:
      - rhel-server-rhui-rhscl-7-rpms
      - rhel-7-server-rhui-extras-rpms
    tower_manage_server: "{{ tower_fqdn }}"
  roles:
    - ansible-tower-manage

...
