---
# Playbook to deploy Ansible Tower

- name: Install Tower to VM
  hosts: tower
  become: true
  vars:
    tower_fqdn: https://tower.tompage.dev
    tower_manage_base_packages:
      - ansible-tower-cli
      - gcc
      - rsync
      - python-devel
      - krb5-devel
      - krb5-libs
      - krb5-workstation
    tower_manage_aws_rhui_repos:
      - rhel-server-rhui-rhscl-7-rpms
      - rhel-7-server-rhui-extras-rpms
    tower_manage_server: "{{ tower_fqdn }}"
    tower_manage_install_certs: true

  pre_tasks:
    - name: Add tower-cli repo
      yum_repository:
        name: ansible-tower-cli
        description: Tower-cli repo
        baseurl: https://releases.ansible.com/ansible-tower-cli/rpm/epel-7-x86_64/
        gpgcheck: false
        enabled: true
        sslverify: false

  roles:
    - ansible-tower-manage

...
